name: Bunka Code Checking

on:
  push:
    branches: ["refacto_dev"]
  pull_request:
    branches: ["refacto_dev"]
permissions:
  contents: read

jobs:
  build:
    #runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9, 3.10.11]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 #V4
      - name: Set up python
        uses: actions/setup-python@v1 #V5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Running code testing
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: make check
