name: Bunka Code Checking

on:
  push:
    branches: ["refacto_dev"]
  pull_request:
    branches: ["refacto_dev"]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Install Spacy Model
        run: python -m spacy download en_core_web_sm
      - name: Running code testing
        run: make check
