name: Bunka Code Checking

on:
  push:
    branches: ["refacto_dev"]
  pull_request:
    branches: ["refacto_dev"]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Running code testing
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: make check
