name: Bunka Code Checking

on:
  push:
    branches: ["refacto_sys/pip"]
  pull_request:
    branches: ["refacto_sys/pip"]
permissions:
  contents: read

jobs:
  build:
    #runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 #V4
      - name: Set up python
        uses: actions/setup-python@v1 #V5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install bunkatopics==0.43.1
      - name: Running code testing
        run: python -m unittest tests/test_bunka_package.py
